# 激活actuator 部分端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,beans
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://rm-8vbi0k952c59x6m629o.mysql.zhangbei.rds.aliyuncs.com:3306/pbcustmgt?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pbcustmgt
    password: pbcustmgt1@3
    type: com.alibaba.druid.pool.DruidDataSource
#  redis:
#    host: 39.99.209.133
#    port: 6379
#    password: redis#123
#    timeout: 5000
#    sentinel:
#      nodes: 127.0.0.1:26379
#      master: test
logging:
  config: classpath:log4j2/log4j2-spring-dev.xml

#自定义缓存参数
cache:
  expirationTime: 2
  maxsize: 100
